// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Vy4BAneT-yImPtShfSiIe5h3OQyheHc',
    appId: '1:1027635304123:web:f2c56d3f2a2ee20c867b9e',
    messagingSenderId: '1027635304123',
    projectId: 'e-commerce-5a79e',
    authDomain: 'e-commerce-5a79e.firebaseapp.com',
    storageBucket: 'e-commerce-5a79e.firebasestorage.app',
    measurementId: 'G-YWM85X4H14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWvscSWpRr5WI2pft-jVUI0Qs062ZAkS8',
    appId: '1:1027635304123:android:b50c4ffdfb132790867b9e',
    messagingSenderId: '1027635304123',
    projectId: 'e-commerce-5a79e',
    storageBucket: 'e-commerce-5a79e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2TRlswC_jmhDcAzxAeObb62JlrGAHe90',
    appId: '1:1027635304123:ios:b68c725f8ce13d4c867b9e',
    messagingSenderId: '1027635304123',
    projectId: 'e-commerce-5a79e',
    storageBucket: 'e-commerce-5a79e.firebasestorage.app',
    androidClientId: '1027635304123-gguqbomff3ptu0hkjiv8l4d0ndv2m7fv.apps.googleusercontent.com',
    iosClientId: '1027635304123-dau459sva6396i4msg08hi2hbv4re2on.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Vy4BAneT-yImPtShfSiIe5h3OQyheHc',
    appId: '1:1027635304123:web:aa6794218e0f814f867b9e',
    messagingSenderId: '1027635304123',
    projectId: 'e-commerce-5a79e',
    authDomain: 'e-commerce-5a79e.firebaseapp.com',
    storageBucket: 'e-commerce-5a79e.firebasestorage.app',
    measurementId: 'G-CB434KEQL4',
  );

}